services:
  api:
    image: ${DOCKER_REGISTRY-}api
    build:
      context: .
      dockerfile: Bootstrapper/Api/Dockerfile

  eshopdb:
    image: postgres

  distributedcache:
    image: redis

  seq:
    image: datalust/seq:latest

  messagebus:
    image: rabbitmq:management

volumes:
  postgres_eshopdb:
